// Code generated by protoc-gen-go-http. DO NOT EDIT.

package v1

import (
	"context"

	http "github.com/go-kratos/kratos/v2/transport/http"
)

type GreeterHTTPServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
}

func RegisterGreeterHTTPServer(s *http.Server, srv GreeterHTTPServer) {
	r := s.Route("/")
	r.POST("/helloworld/{name}", _Greeter_SayHello0_HTTP_Handler(srv))
}

func _Greeter_SayHello0_HTTP_Handler(srv GreeterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HelloRequest
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, Greeter_SayHello_FullMethodName)
		h := ctx.Middleware(func(c context.Context, req interface{}) (interface{}, error) {
			return srv.SayHello(c, req.(*HelloRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HelloReply)
		return ctx.Result(200, reply)
	}
}
