// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"demo/internal/biz"
	"demo/internal/conf"
	"demo/internal/data"
	"demo/internal/server"
	"demo/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// wireApp initializes the application.
func wireApp(confServer *conf.Server, confData *conf.Data, auth *conf.Auth, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase)
	userRepo := data.NewUserRepo(dataData, logger)
	userLoginLogRepo := data.NewUserLoginLogRepo(dataData, logger)
	string2 := biz.ProvideJWTSecret(auth)
	authUseCase := biz.NewAuthUseCase(userRepo, userLoginLogRepo, logger, string2)
	authService := service.NewAuthService(authUseCase, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, authService, logger)
	grpcServer := server.NewGRPCServer(confServer, greeterService, authService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
